//  PrivateConstants.h
//
//  `bundle install`
//  `./appkeeper.sh yonghuitest`
//
//  Created by lijunjie on 16/04/08.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghuitest]
// automatic generated by app_keeper.rb
#ifndef PrivateConstants_h
#define PrivateConstants_h

#define kAppCode          @"yonghui"
#define kBaseUrl1         @"http://localhost:4567"
#define kInitPassword     @"123456"
#define kLoginSlogan      @"融合共享，成于至善"


// 开发环境
#define kBaseUrl          @"http://yonghui-dev.idata.mobi"
#define kPgyerUrl         @"https://www.pgyer.com/yh-dev-i"
#define kPgyerAppId       @"bff6bd180e9818192b4c7de21394a6c4"
#define kBUGLYID          @"4b3788f0b7"
#define kGAODEMAP         @"79d9aaf3007a0bea53bf51d3e2901552"
#define kUMAppId          @"57b522fee0f55a7ba8001606"
#define kWXAppId          @"wxc48d00458356ccb6"
#define kWXAppSecret      @"2ee0c11d37b992dc882c7fe967469fa7"


//Bugly
// 测试环境
// bugly
//#define kBUGLYID          @"161d46f427"
//#define kBaseUrl         @"http://yonghui-test.idata.mobi"
//#define kGAODEMAP          @"ee6284cf9b216800309aa7639a2fb172"
//#define kPgyerAppId       @"1d835e3e87539d37790403d1e5f26ef6"
//#define kPgyerUrl         @"http:www.pgyer.com/yh-test-i"
//#define kUMAppId          @"57b522fee0f55a7ba8001606"
//#define kWXAppId          @"wxc48d00458356ccb6"
//#define kWXAppSecret      @"2ee0c11d37b992dc882c7fe967469fa7"


// 正式环境
//#define kBUGLYID          @"4456d2d6b1"
//#define kGAODEMAP          @"ea3863d455fc25dc55e37f89387b4cc5"
//#define kBaseUrl          @"http://yonghui.idata.mobi"
//#define kPgyerAppId       @"7586e8c77ceadd3240c5e243e9d0c391"
//#define kPgyerUrl          @"https://www.pgyer.com/yh-i"
//#define kUMAppId          @"56f9ebad67e58eb4990012c8"
//#define kWXAppId          @"wx9173274e2ea0d365"
//#define kWXAppSecret      @"22a92f9b55da6357e02e25f069ad7883"


//基础设置
#define kDashboardAd      NO

#define kDropMenuScan     YES
#define kDropMenuVoice    YES
#define kDropMenuSearch   YES
#define kDropMenuUserInfo NO
// token
#define  API_TOKEN        @"e0e57df4d40eab55c7eb8bdd851ae328"

#define kTabBar           YES
#define kTabBarKPI        YES
#define kTabBarAnalyse    YES
#define kTabBarApp        YES
#define kTabBarMessage    YES

#define kSubjectComment   YES
#define kSubjectShare     YES

#endif /* PrivateConstants_h */
